# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: kanban-rs.kanban
PackageVersion: 0.10.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: kanban.exe
  PortableCommandAlias: kanban
- RelativeFilePath: kanban-mcp.exe
  PortableCommandAlias: kanban-mcp
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kanban-rs/kanban/releases/download/v0.10.0/kanban-v0.10.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 50AC1906954A935134EFFE5494E9CDE3D90CF664A1FA4657513597B9AC4B7C34
ManifestType: installer
ManifestVersion: 1.12.0
